# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2c942c4e8fa4fcaf3231e9c25333c94b9b81f7245b21f3bd5eb77873635d29a53f46ece573e0c28656e5f9c788d903063e5d541d5544ff306c373d28637acf7

test:
  secret_key_base: a366039721383f93eda5608cbf9d6547d15d9951deb044ccd0854744f1004641940ba5353f4757c3d17df7e8a8144f926ced9b860a120440d00412ff0b05a020

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
